const tabs=[...document.querySelectorAll('.game-tabs button')];
const panels=[...document.querySelectorAll('.game-panel')];
tabs.forEach(b=>b.addEventListener('click',()=>{tabs.forEach(x=>x.classList.remove('active'));panels.forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.game).classList.add('active')}));

const classes={
  'LVTHIER':{CRAFT:99,GEAR:98,CODE:44,CHAOS:87},'MV SICIAN':{TONE:97,GEAR:99,RHYTHM:91,SLEEP:21},'PROGRAMMER':{CODE:96,DEBUG:84,SEMICOLON:72,SLEEP:18},'FOVNDER':{VISION:91,CASHFLOW:33,BRANDING:88,CHAOS:93},'TRICKER':{MOTION:92,GRAVITY:41,BRAVERY:89,KNEES:64},'SWIMMER':{ENDVRANCE:91,WATER:100,CHLORINE:88,HAIR:22}}
const cg=document.getElementById('class-grid'),cr=document.getElementById('class-result');
Object.entries(classes).forEach(([name,stats])=>{let b=document.createElement('button');b.textContent=name;b.onclick=()=>cr.innerHTML=`<strong>${name}</strong>`+Object.entries(stats).map(([k,v])=>`<div class="statline"><span>${k}</span><b>${v}</b></div>`).join('');cg.appendChild(b)});

const quiz=[['Pick one.',['Practice bass for 3 hours','Start another project','Go to sleep on time'],0],['A guitar has a cosmetic defect.',['Ignore it','AB epoxy time','Sell every instrument'],1],['Best portfolio section?',['Only programming','Everything everywhere','Corporate mission statement'],1],['Hydration?',['500 mL','4 L','What is water'],1],['A hobby is becoming manageable.',['Enjoy balance','Add three adjacent hobbies','Quit everything'],1]];
let qi=0,qs=0;const qb=document.getElementById('quiz-box');function drawQ(){if(qi>=quiz.length){qb.innerHTML=`<div class="result-box">CHARLIE SCORE: <b>${qs}/${quiz.length}</b><br>${qs>=4?'CONCERNINGLY CHARLIE.':qs>=2?'CHARLIE-ADJACENT.':'FUNCTIONING NORMALLY.'}</div><button class="game-button" id="quiz-restart">AGAIN</button>`;document.getElementById('quiz-restart').onclick=()=>{qi=0;qs=0;drawQ()};return}let [q,opts,ans]=quiz[qi];qb.innerHTML=`<div class="quiz-q">${q}</div><div class="quiz-options">${opts.map((o,i)=>`<button data-i="${i}">${o}</button>`).join('')}</div>`;qb.querySelectorAll('button').forEach(b=>b.onclick=()=>{if(+b.dataset.i===ans)qs++;qi++;drawQ()})}drawQ();

const inst=[
 {s:'FOUR STRINGS · TWO SINGLE-COIL PICKUPS · OFFSET WAIST · 34-INCH SCALE',a:'JAZZ BASS',o:['JAZZ BASS','TELECASTER','MANDOLIN']},
 {s:'SEVEN STRINGS · DOUBLE-CUT BODY · TREMOLO · EXTENDED RANGE',a:'7-STRING GUITAR',o:['BARITONE UKULELE','7-STRING GUITAR','UPRIGHT BASS']},
 {s:'SIX STRINGS · 35-INCH SCALE · DEEP BODY · MULTI-OCTAVE BASS RANGE',a:'6-STRING BASS',o:['6-STRING BASS','CLASSICAL GUITAR','BANJO']},
 {s:'NYLON STRINGS · THIN BODY · SOUNDHOLE-LESS STAGE DESIGN',a:'NYLON ELECTRIC',o:['NYLON ELECTRIC','DOBRO','JAZZMASTER']}
];let ii=0;const st=document.getElementById('spec-text'),io=document.getElementById('instrument-options'),ir=document.getElementById('instrument-result');function drawI(){let x=inst[ii%inst.length];st.textContent=x.s;io.innerHTML='';x.o.forEach(o=>{let b=document.createElement('button');b.textContent=o;b.onclick=()=>ir.textContent=o===x.a?'CORRECT. GEAR BRAIN DETECTED.':`NO. IT WAS ${x.a}.`;io.appendChild(b)});ir.textContent='READ THE SPECS. GUESS THE INSTRUMENT.'}document.getElementById('next-instrument').onclick=()=>{ii++;drawI()};drawI();

let pickTimer=null,pickScore=0,pickTime=20;const arena=document.getElementById('pick-arena'),target=document.getElementById('pick-target'),ps=document.getElementById('pick-score'),pt=document.getElementById('pick-time');function movePick(){let x=Math.random()*(arena.clientWidth-60),y=Math.random()*(arena.clientHeight-70);target.style.left=x+'px';target.style.top=y+'px'}target.onclick=()=>{pickScore++;ps.textContent=pickScore;movePick()};document.getElementById('pick-start').onclick=()=>{clearInterval(pickTimer);pickScore=0;pickTime=20;ps.textContent=0;pt.textContent=20;target.style.display='block';movePick();pickTimer=setInterval(()=>{pickTime--;pt.textContent=pickTime;if(pickTime<=0){clearInterval(pickTimer);target.style.display='none'}},1000)};

let hp=100;const hpb=document.getElementById('boss-hp'),bs=document.getElementById('boss-status');const lines=['CSS specificity retaliates.','The navbar breaks at 390px.','GitHub Pages refuses to elaborate.','You forgot one closing div.','The rubric approaches.'];document.getElementById('boss-attack').onclick=()=>{if(hp<=0)return;hp=Math.max(0,hp-(8+Math.floor(Math.random()*16)));hpb.style.width=hp+'%';bs.textContent=hp?lines[Math.floor(Math.random()*lines.length)]:'DEPLOY SUCCESSFUL. THE DEADLINE HAS BEEN DEFEATED.'};document.getElementById('boss-reset').onclick=()=>{hp=100;hpb.style.width='100%';bs.textContent='It is 11:42 PM. The deploy is broken.'};

const interests=['BASSIST','GUITARIST','PROGRAMMER','AI RESEARCHER','LVTHIER','ENGINEER','TRICKER','SWIMMER','FOVNDER','COOK','ANIME ENJOYER','CAT SERVANT','LINGVISTICS NERD'];document.getElementById('randomize').onclick=()=>{document.getElementById('random-output').textContent=[...interests].sort(()=>Math.random()-.5).slice(0,4).join(' + ')};
